---
title: "Conclusion"
---

In accordance with the statistical analysis result above, the realistic studies and facts also support the conclusion that the divorce rate varies with income levels. Becker’s theory of divorce (1991) demonstrates that the increase in female earnings over time may be partly responsible for the increase in the divorce rate. The theory is derived from basic economic theory, stating that if the couples are both high-income earners, the gain from marriage is relatively low and they would be able to maintain their living standards after the divorce (Liu& Vikat, 2007). It helps explain why there is a sharp increase in the likelihood of divorce from 9.5376% (low-income group) to 58.4% (median-income group). 

Nevertheless, the analysis gives a surprising result in high-income group. The possibility of divorce even decreases by 3% from median-income group to high-income group, which does not go along with the conclusion of the theory above. For married couples, more generous cash transfers may have a stabilization effect and relax financial constraints and fewer arguments that lead to divorce (Hankins and Hoekstra, 2011). The abnormality could also be explained by the income effect from the economic theory: higher family income improves living quality therefore enhances marital stability.
 
Considering the effect of age, older people’s divorce rate is less correlated with their income level, the divorce probability is between 14% and 16.4%. While younger people’s divorce probabilities are more volatile between different income groups. Young people in low-income group have a probability of 5.24% of divorce which is almost 4% lower than medium-income group. 

In the current society, old people need more care, accompany as well as love, so a fully functional family is a perfect solution to fulfill those personal needs (Trust, 2017). Compared to younger people, older people have a stronger needs on family love. However, based on the statistical result, older people have a higher probability of getting divorced because older people are facing fewer financial constraints than youngsters due to their accumulated savings. In addition, there is a large variety of substitutions that can lower the importance of being in marriage, such as daycare centers and nursing homes. If they are not satisfied with their current marriages, divorce is an easy option for them and they have the ability to pursue other substitutions. Thus, leading to the conclusion that older people’s divorce rate is less affected by income-level.

The final factor that has a significant influence on income and divorce rate is whether there is a child in the family. According to the 2018 divorce statistics, the divorce rate for couples with children is as much as 40 percent lower than for those without children. There is a disputable argument which indicates that kids increased divorce risks because they reduced the time for married couples to focus on themselves and on each other. However, it doesn’t coincide with the IPUMS data. The statistical result shows that children actually bring down the divorce rate in all three income groups and the high-income group is most affected by the existence of children. The probability of divorce in high-income group decreases by 4.4% if there is at least one child in the family.

In modern American family, according to a new Pew Research Center survey, children from richer families enrolled in ballet, soccer and after-school programs, while children from poorer families spend their time at home or grow up in neighborhoods (Miller, 2015). The different upbringings require different inputs and efforts from parents. Therefore, children from high-income families need two parents to “create” a competitive future for them. In low-income families, when the survival problem is above all, the happiness and future of children could not affect much of parents’ decision to divorce.

In conclusion, medium-income families is exposed to a higher probability of getting divorced than low-income and high-income families. Both age and children in the family can have an influence on the divorce rate, although the effect is different across income groups. Our study suggests that if people want to have a lower probability of getting divorced while maintaining a high living standard, they should try working up to high-income group and have at least one child in the family. Our study is still a preliminary study on the effect on the divorce rate when factoring income, age and children, and we encourage further studies on relative issues.

