---
title: "Procedure"
---

**1. Data Preparation**
(a) Divide all people into three income groups based on tertile. (Low income “1”, Medium income “2”, High income “3”). Low income is when people’s wages less than 14,400 USD. Medium income is when people’s wages between 14,400 USD and 42,000 USD. High income is when people’s wages higher than 42,000 USD.
(b) Drop the people whose age are below 17 years old. Because non-adults’ income data is not persuasive enough for this research.
(c) Define a new variable “divorce” as 1 if marital status is divorce , and 0 if marital status is other than divorce.
(d) Report an average divorce rate in the sample.
(e) Define a new variable “age group” as 0 (young) if  younger or equal to 50 years old, 1 (old) if  older than 50 years old.
(f) Define a new variable “child” as 0 if with no children (the number of children =0), 1 if with children.

**2. Construct logistic regression and make analysis: **find out whether the marital status influence Income. Assumptions of this model are as follows: 
<br />(a). There exists a linear relationship between the logit of the outcome and each predictor variables. 
<br />(b). Without influential values in the continuous predictor. 
<br />(c). No high intercorrelations among the predictors.
	We set the confidence interval at 95%.  If a variable’s p-value less than 0.05, we believe it is significant enough to reject the null hypothesis.

**3. Construct multiple regression and make analysis: **find out whether marital status will be affected by people’s income, age, the number of children. Assumptions of this model are as follows: 
<br />(a). There exists a linear relationship between the logit of the outcome and each independent predictor variables. 
<br />(b). No Multicollinearity 
<br />(c). Homoscedasticity.
	We set the confidence interval at 95%.  If a variable’s p-value less than 0.05, we believe it is significant enough to reject the null hypothesis.
	
**4. Summarize the results and make final conclusion.**


