---
title: "Reference and List of Author"
---

***Reference***

Becker, Gary S. (1991). A Treatise on the Family. Cambridge, MA: Harvard University Press, 2 nd edition;

Divorce Statistics and Facts | What Affects Divorce Rates in the U.S.?. (2019). Retrieved 18 December 2019, from https://www.wf-lawyers.com/divorce-statistics-and-facts/

Hankins, S., & Hoekstra, M. (2010). Lucky in Life, Unlucky in Love? The Effect of Random Income Shocks on Marriage and Divorce. *SSRN Electronic Journal*. doi: 10.2139/ssrn.1629878

Himmelweit, Susan, Cristina Santos, Almudena Sevilla and Catherine Sofer (2013). Sharing of resources within the family and the economics of household decision making. Journal of Marriage and Family, 75(3): 625–639. doi: 10.1111/jomf.12032;

Liu, G., & Vikat, A. (2007). Does Divorce Risk in Sweden depend on Spouses' Relative Income? A Study of Marriages from 1981 to 1998. *Canadian Studies In Population*, 34(2), 217. doi: 10.25336/p6pd0b

Miller, C. (2015). Class Differences in Child-Rearing Are on the Rise. Retrieved 18 December 2019, from https://www.nytimes.com/2015/12/18/upshot/rich-children-and-poor-ones-are-raised-very-differently.html

Taylor, V. (2018). Actually, Having Kids * Doesn't * Increase Your Chances of Divorce — But Here's What Does. Retrieved 18 December 2019, from https://www.romper.com/p/does-having-kids-statistically-increase-your-chances-of-divorce-its-complicated-9064206

Trust, S. (2017). Old people need more care as well as love. In recent times, it is impossible for their children to take care of their parents. Retrieved 18 December 2019, from https://yourstory.com/mystory/636d17dccc-old-people-need-more-c

***List of Arthor***

Shiqing Lin
<br />Mengxi Zhang
<br />Qiuyi Chen
<br />Yiyun Ding
